sudo: required
env:
  matrix:
    - DISTRIBUTION=centos-5
    - DISTRIBUTION=centos-6
    - DISTRIBUTION=centos-7
    - DISTRIBUTION=debian-7
    - DISTRIBUTION=debian-8
    - DISTRIBUTION=fedora-23
    - DISTRIBUTION=fedora-24
    - DISTRIBUTION=opensuse-13.1
    - DISTRIBUTION=opensuse-13.2
    - DISTRIBUTION=opensuse-42.1
    - DISTRIBUTION=opensuse-tumbleweed
    - DISTRIBUTION=ubuntu-12.04
    - DISTRIBUTION=ubuntu-14.04
    - DISTRIBUTION=ubuntu-15.10
    - DISTRIBUTION=ubuntu-16.04
services:
  - docker
script:
  - ./test-distribution.sh $DISTRIBUTION
