sudo: required
env:
  matrix:
    - DISTRIBUTION=ubuntu
    - DISTRIBUTION=debian
    - DISTRIBUTION=opensuse
    - DISTRIBUTION=centos
    - DISTRIBUTION=fedora
services:
  - docker
script:
  - ./test-distributions.sh
